---
- name: ensure minio storage directory
  file:
    dest: '{{ minio_storage_dir }}'
    state: directory

- name: run minio container
  docker_container:
    state: started
    restart: yes
    recreate: yes
    pull: true
    name: '{{ minio_container_name }}'
    image: '{{ minio_container_image }}'
    restart_policy: always
    volumes: '{{ minio_container_volumes }}'
    env: '{{ minio_container_env }}'
    networks: '{{ minio_container_networks }}'
    links: '{{ minio_container_links }}'
    command: '{{ minio_container_command }}'
    published_ports: '{{ minio_container_published_ports }}'
