---
- name: run minio mirror dirs containers
  docker_container:
    state: started
    recreate: yes
    restart: yes
    name: '{{ item.container_name }}'
    image: minio/mc
    restart_policy: always
    volumes:
      - '{{ item.source }}:/export:ro'
    env:
      MC_HOSTS_target: '{{ item.target }}'
    networks: '{{ minio_networks }}'
    links: '{{ minio_links }}'
    command: mirror {{ item.flags }} /export target/{{ item.bucket }}
  with_items: '{{ minio_mirror_dirs }}'

- name: run minio mirror buckets containers
  docker_container:
    state: started
    recreate: yes
    restart: yes
    name: '{{ item.container_name }}'
    image: minio/mc
    restart_policy: always
    env:
      MC_HOSTS_source: '{{ item.source }}'
      MC_HOSTS_target: '{{ item.target }}'
    networks: '{{ minio_networks }}'
    links: '{{ minio_links }}'
    command: mirror {{ item.flags }} source/{{ item.bucket | default('') }} target/{{ item.bucket | default('') }}
  with_items: '{{ minio_mirror_instances }}'
